# Generated by Django 4.1.4 on 2022-12-28 03:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('cod_prod', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('vigencia', models.IntegerField()),
                ('cantidad', models.IntegerField(blank=True)),
                ('valor_compra', models.IntegerField(blank=True, null=True)),
                ('valor_venta', models.IntegerField(blank=True, null=True)),
                ('fecha_actualiza', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id_devolucion', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_cliente', models.CharField(blank=True, max_length=150, null=True)),
                ('motivo', models.CharField(blank=True, max_length=150, null=True)),
                ('estado', models.BooleanField()),
                ('fecha', models.DateTimeField()),
                ('id_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.producto')),
            ],
        ),
    ]
