# Generated by Django 4.1.4 on 2022-12-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle_Factura',
            fields=[
                ('cod_fac', models.IntegerField(primary_key=True, serialize=False)),
                ('detalle_producto', models.CharField(blank=True, max_length=42, null=True)),
                ('cantidad', models.IntegerField(blank=True)),
                ('precio_unitario', models.IntegerField(blank=True)),
                ('precio_total', models.IntegerField(blank=True)),
                ('cliente', models.CharField(blank=True, max_length=50)),
                ('direccion_envio', models.ImageField(blank=True, upload_to='')),
                ('telefono', models.CharField(max_length=50)),
                ('fecha_compra', models.DateTimeField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Metodos_pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
