# Generated by Django 4.1.4 on 2023-01-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_factura',
            name='direccion_envio',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
